# Change these first
owner: digitaltucan # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

user-agent: digitaltucan # your-github-username

sites:
  - name: sftp
    check: "tcp-ping"
    url: $SERVER_IP_1
    port: 2221
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: web
    check: "tcp-ping"
    url: $SERVER_IP_1
    port: 443
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: db
    check: "tcp-ping"
    url: $SERVER_IP_1
    port: 3306
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: smtps
    check: "tcp-ping"
    url: $SERVER_IP_1
    port: 465
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: submission
    check: "tcp-ping"
    url: $SERVER_IP_1
    port: 587
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: imaps
    check: "tcp-ping"
    url: $SERVER_IP_1
    port: 993
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: webmail
    check: "tcp-ping"
    url: $SERVER_IP_1
    port: 443
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: dns
    check: "tcp-ping"
    url: lina.ns.cloudflare.com
    port: 53
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png
  - name: backup
    check: "tcp-ping"
    url: u285001.your-storagebox.de
    port: 22
    icon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/icon.png

    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.digitaltucan.de
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/logo.svg
  name: ""
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
    # - title: Status
    #   href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
  
  favicon: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/favicon.png
  faviconSvg: https://raw.githubusercontent.com/digitaltucan/upptime/master/assets/favicon.svg
  # themeUrl: https://status.digitaltucan.de/assets/custom.css
  theme: light
  css: "
  
  :root {
    --body-background-color: #f9f9f9;
    --body-text-color: #002626;
    --card-background-color: #ffffff;
    --nav-background-color: #f9f9f9;
    --nav-border-bottom-color: #f9f9f9;
    --nav-current-border-bottom-color: #1abc9c;
    --card-border-color: #d8e8e4;
    --down-border-left-color: #eb3b5a;
    --down-background-color: #ffd0d2;
    --degraded-border-left-color: #f7b731;
    --up-border-left-color: #20bf6b;
    --tag-color: #ffffff;
    --tag-up-background-color: #20bf6b;
    --tag-down-background-color: #eb3b5a;
    --tag-degraded-background-color: #f7b731;
    --change-background-color: #f7b731;
    --error-button-border-color: #1a46ad;
    --error-button-background-color: #3867d6;
    --error-button-color: #ffffff;
    --submit-button-border-color: #1a46ad;
    --submit-button-background-color: #3867d6;
    --submit-button-color: #ffffff;
    --graph-opacity: 1;
    --graph-filter: none;
  }

  .logo {
    margin-top: 2rem;
  }
  
  article {
    border-radius: 0;
    padding: 2rem;
  }
  
  
  "

i18n:
  # footer: "[digitaltucan](https://digitaltucan.de)"
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
